# Generated by Django 5.1.7 on 2025-04-01 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0006_category_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaigns/')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.project')),
            ],
        ),
    ]
