# Generated by Django 5.1.7 on 2025-04-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0010_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
