# Generated by Django 5.1.7 on 2025-04-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0015_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
