# Generated by Django 5.1.7 on 2025-04-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0007_campaignimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
    ]
